# language: node_js
# node_js:
# - '7'
# services:
# - mysql
# env:
#   global:
#   - NODE_ENV=test
#   - APP_NAME=MASTER_CONDO
#   - APP_PORT=3000
#   - BASE_URL=http://127.0.0.1:3000
#   - MYSQL_HOST=127.0.0.1
#   - MYSQL_PORT=3306
#   - MYSQL_USERNAME=root
#   - MYSQL_PASSWORD=
#   - MYSQL_DBNAME=condo_admin
#   - MYSQL_ENGINE=InnoDB
#   - MYSQL_CHARSET=utf8mb4
#   - MYSQL_COLLATE=utf8mb4_unicode_ci
#   - ACCESS_TOKEN_LIFE_TIME=2592000
#   - EMAIL_VERIFICATION_TOKEN_LIFE_TIME=259200
#   - EMAIL_RECOVERY_TOKEN_LIFE_TIME=259200
# before_install:
# - mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DBNAME CHARACTER SET $MYSQL_CHARSET COLLATE $MYSQL_COLLATE;"
# - npm run db:migrate:up
# script:
# - npm run lint
# - npm run test
# cache:
#   directories:
#   - node_modules
deploy:
  provider: codedeploy
  access_key_id: AKIAINXCQEZAAG4RKJQA
  secret_access_key:
    secure: gkIL6jdI+jqMDDRW9YsKgQZxvLs4MT9IKegWWkpvvTfIMPiU9fFjUZNtUQ0FjBP8uzvgrPXvKpywMxbCYGeG/d3rogCtRBJEaFIQWR56XrLRGozb/c5bmlxXqGA9RjVfqpEQkb8HNnjbDIvzGcJiXV7KIxFIJ7weZZnbd6Qn+noN+XWGNRPGEZv6cLyUsG/5F5fsvor47ILMFfP1a0zL2euXHQmq2JUHPWG3ACc3CRHFUVXKWGYctSze6nYqNLCv/A2p6HKqtj5b7LZKXW02WAEF2CsE6wtxVYaiXUBZrwRXjztF/RYV5Cb9YqaMiLplknfFS50PhzIMoLU+lVh1fU1pFkqn8Ec79IEGaSd6UM1W9THi3bNi/qh1PgusHxWd2AhlluixmCv5PUxLVeS9gTzHsuuJEdiTxm9TKCE3EFLJLGDu1WUrA+jpU7y3BzZAcuG+jxQwl/NveClE7ENiBIQEaY4awCOCAjy4GqzcpCqbpDRMDKGMHcoIjtc6e/40Vw2lC8DTho1Gs77czBne9K0Uw4hydJ9iTLLJZ1KCvFyyeeoH0ncUEo/lukcqHgOJbrDQTElUDYqYaU5jhoMru4/fPYxPEzAUCztQqvvuJjzzTBFZol9PMfwTlH+XHuQsAS/lgFaKxxDGaW5h9myKJRDQxU4TYpS7NejHJ+NEnj4=
  region: us-west-2
  application: CondoDeployment
  deployment_group: CondoAdmin-API-Deployment
  revision_type: github
  wait-until-deployed: true
  on:
    repo: kulltaa/masterCondo
    branch: master
